import * as SC from "effect/Schema"

export const VoiceType = SC.Union(
    SC.Literal("FemaleArgonian"),
    SC.Literal("FemaleChild"),
    SC.Literal("FemaleCommander"),
    SC.Literal("FemaleCommoner"),
    SC.Literal("FemaleCondescending"),
    SC.Literal("FemaleCoward"),
    SC.Literal("FemaleDarkElf"),
    SC.Literal("FemaleElfHaughty"),
    SC.Literal("FemaleEvenToned"),
    SC.Literal("FemaleKhajiit"),
    SC.Literal("FemaleNord"),
    SC.Literal("FemaleOldGrumpy"),
    SC.Literal("FemaleOldKindly"),
    SC.Literal("FemaleOrc"),
    SC.Literal("FemaleShrill"),
    SC.Literal("FemaleSultry"),
    SC.Literal("FemaleUniqueGhost"),
    SC.Literal("FemaleYoungEager"),
    SC.Literal("MaleArgonian"),
    SC.Literal("MaleBandit"),
    SC.Literal("MaleBrute"),
    SC.Literal("MaleChild"),
    SC.Literal("MaleCommander"),
    SC.Literal("MaleCommoner"),
    SC.Literal("MaleCommonerAccented"),
    SC.Literal("MaleCondescending"),
    SC.Literal("MaleCoward"),
    SC.Literal("MaleDarkElf"),
    SC.Literal("MaleDrunk"),
    SC.Literal("MaleElfHaughty"),
    SC.Literal("MaleEvenToned"),
    SC.Literal("MaleEvenTonedAccented"),
    SC.Literal("MaleGuard"),
    SC.Literal("MaleKhajiit"),
    SC.Literal("MaleNord"),
    SC.Literal("MaleNordCommander"),
    SC.Literal("MaleOldGrumpy"),
    SC.Literal("MaleOldKindly"),
    SC.Literal("MaleOrc"),
    SC.Literal("MaleSlyCynical"),
    SC.Literal("MaleSoldier"),
    SC.Literal("MaleUniqueGhost"),
    SC.Literal("MaleWarlock"),
    SC.Literal("MaleYoungEager")
)

export type VoiceType = typeof VoiceType.Type
